language: haskell
before_install:
  - git clone https://github.com/galoisinc/ivory
  - export IVORY_REPO=$PWD/ivory
install:
  - cabal install alex
  - cabal install happy
script:
  - IVORY_REPO=$IVORY_REPO make $ENV_TEST_TARGET
ghc:
  - 7.6.3
  - 7.8.3
env:
  - ENV_TEST_TARGET=tower
  - ENV_TEST_TARGET=tower-statemachine
  - ENV_TEST_TARGET=tower-config
  - ENV_TEST_TARGET=tower-aadl
