sudo: false
language: c

cache:
  directories:
    - $HOME/.stack

matrix:
  include:
    - env: GHCVER=7.8.4 STACK_YAML=stack-7.8.yaml
      addons: {apt: {packages: [ghc-7.8.4], sources: [hvr-ghc]}}
    - env: GHCVER=7.10.3 STACK_YAML=stack.yaml
      addons: {apt: {packages: [ghc-7.10.3], sources: [hvr-ghc]}}
    - env: GHCVER=8.0.2 STACK_YAML=stack-8.0.yaml
      addons: {apt: {packages: [ghc-8.0.2], sources: [hvr-ghc]}}

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
  - ghc --version
  - stack --version
install:
  # Check out depenendency repos, then check out the branch that
  # matches the current branch name in this repo. If one doesn't
  # exist, don't fail, in case we're branched in this repo but just
  # depending on master elsewhere.
  #
  # Travis seems to have no problem with the multi-line if above,
  # but barfs when we format this one nicely.
  - for repo in ivory; do git clone https://github.com/galoisinc/$repo; (cd $repo; git checkout $TRAVIS_BRANCH) || true; export ${repo^^}_REPO=$PWD/$repo; done
  # tweak the relative paths in stack.yaml
  - export STACK_YAML=$PWD/$STACK_YAML
  - sed -i "s;\.\./;$PWD/;g" $STACK_YAML
script:
  - make travis-test
