# Allow (faster) Docker builds
sudo: false

language: haskell
before_install:
  - git clone https://github.com/galoisinc/ivory
  - export IVORY_REPO=$PWD/ivory
install:
  - cabal install alex happy
script:
  - IVORY_REPO=$IVORY_REPO make $ENV_TEST_TARGET
ghc:
  - 7.8
env:
  - ENV_TEST_TARGET=tower
  - ENV_TEST_TARGET=tower-config
  - ENV_TEST_TARGET=tower-aadl
  - ENV_TEST_TARGET=tower-hal
